# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availible',
            new_name='available',
        ),
    ]
